substitutions:
  _REGION: us-central1
  _TEAM: team-a
  _TARGET_PROJECT_ID: dev-project-305220
  _CLOUDSDK_CONTAINER_CLUSTER: krmapihost-kcc-cicd
steps:
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    sed -i s/PROJECT_ID/$PROJECT_ID/g ${_TEAM}/resources/staging/*
    sed -i s/PROJECT_ID/$PROJECT_ID/g ${_TEAM}/resources/prod/*
    sed -i s/PROJECT_ID/$PROJECT_ID/g ${_TEAM}/deploy/*
    sed -i s/TEAM/${_TEAM}/g ${_TEAM}/skaffold.yaml
    sed -i s/REGION/${_REGION}/g ${_TEAM}/deploy/*
    sed -i s/CLUSTER_NAME/${_CLOUDSDK_CONTAINER_CLUSTER}/g ${_TEAM}/deploy/*
    gcloud alpha deploy apply --file ${_TEAM}/deploy/pipeline.yaml
    gcloud alpha deploy apply --file ${_TEAM}/deploy/staging.yaml
    gcloud alpha deploy apply --file ${_TEAM}/deploy/prod.yaml
    gcloud alpha deploy releases create rel-${SHORT_SHA} \
                        --delivery-pipeline ${_TEAM}-pipeline \
                        --description "$(git log -1  --pretty='%s')" \
                        --annotations "commit_ui=https://github.com/zsais/kcc-cicd/commit/$COMMIT_SHA"

options:
  machineType: E2_HIGHCPU_8
timeout: 3600s
