substitutions:
  _REGION: us-central1
  _TEAM: team-a
  _TARGET_PROJECT_ID: dev-project-305220
  _CLOUDSDK_CONTAINER_CLUSTER: krmapihost-kcc-cicd
steps:
- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    sed -i s/PROJECT_ID/$PROJECT_ID/g ${_TEAM}/resources/dev/*

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=${_TEAM}/resources/dev/
  - --location=${_REGION}
  - --cluster=${_CLOUDSDK_CONTAINER_CLUSTER}

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud config set deploy/region ${_REGION}
    gcloud container clusters get-credentials ${_CLOUDSDK_CONTAINER_CLUSTER} --region ${_REGION}
    kubectl delete -f ${_TEAM}/resources/dev/
options:
  machineType: E2_HIGHCPU_8
timeout: 3600s
