apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: team-a-pipeline
profiles:
- name: staging
  deploy:
    kustomize:
      paths:
      - resources/staging/
- name: prod
  deploy:
    kustomize:
      paths:
      - resources/prod/