apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: team-a-pipeline
profiles:
- name: staging
  deploy:
    kubectl:
      manifests:
      - resources/staging/*.yaml
- name: prod
  deploy:
    kubectl:
      manifests:
      - resources/prod/*.yaml