apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: PROJECT_ID
  name: PROJECT_ID-devdays-autopilot-cluster-dev
spec:
 description: An autopilot cluster
 enableAutopilot: true
 location: us-south1
 releaseChannel:
   channel: REGULAR